Traceback (most recent call last):
  File "/usr/share/miniconda/envs/DevelopmentalRegulation/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/DevelopmentalRegulation/lib/python3.8/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/envs/DevelopmentalRegulation/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/envs/DevelopmentalRegulation/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/envs/DevelopmentalRegulation/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/envs/DevelopmentalRegulation/lib/python3.8/site-packages/nbclient/client.py", line 535, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/DevelopmentalRegulation/lib/python3.8/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/share/miniconda/envs/DevelopmentalRegulation/lib/python3.8/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fix, ax = plt.subplots(figsize=(15,15))

df1 = dfs["Bl71nemr"]
df2 = dfs["ASM318616v1"]
corr = pd.concat([df1, df2], axis=1, keys=['df1', 'df2']).corr().loc['df2', 'df1'].T
*outline, _ = util.get_outline(corr.values)
ax.plot(*outline, color=(1,0,0,.5), linewidth=3)
ax.matshow(corr.values)
for (i, j), z in np.ndenumerate(corr.values):
    ax.text(j, i, '{:0.2f}'.format(z), ha='center', va='center')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
[0;32m/usr/share/miniconda/envs/DevelopmentalRegulation/lib/python3.8/site-packages/pandas/core/indexes/base.py[0m in [0;36mget_loc[0;34m(self, key, method, tolerance)[0m
[1;32m   2890[0m             [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 2891[0;31m                 [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_engine[0m[0;34m.[0m[0mget_loc[0m[0;34m([0m[0mcasted_key[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   2892[0m             [0;32mexcept[0m [0mKeyError[0m [0;32mas[0m [0merr[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32mpandas/_libs/index.pyx[0m in [0;36mpandas._libs.index.IndexEngine.get_loc[0;34m()[0m

[0;32mpandas/_libs/index.pyx[0m in [0;36mpandas._libs.index.IndexEngine.get_loc[0;34m()[0m

[0;32mpandas/_libs/hashtable_class_helper.pxi[0m in [0;36mpandas._libs.hashtable.PyObjectHashTable.get_item[0;34m()[0m

[0;32mpandas/_libs/hashtable_class_helper.pxi[0m in [0;36mpandas._libs.hashtable.PyObjectHashTable.get_item[0;34m()[0m

[0;31mKeyError[0m: 'df2'

The above exception was the direct cause of the following exception:

[0;31mKeyError[0m                                  Traceback (most recent call last)
[0;32m<ipython-input-3-d1ea50e4c040>[0m in [0;36m<module>[0;34m[0m
[1;32m      3[0m [0mdf1[0m [0;34m=[0m [0mdfs[0m[0;34m[[0m[0;34m"Bl71nemr"[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mdf2[0m [0;34m=[0m [0mdfs[0m[0;34m[[0m[0;34m"ASM318616v1"[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 5[0;31m [0mcorr[0m [0;34m=[0m [0mpd[0m[0;34m.[0m[0mconcat[0m[0;34m([0m[0;34m[[0m[0mdf1[0m[0;34m,[0m [0mdf2[0m[0;34m][0m[0;34m,[0m [0maxis[0m[0;34m=[0m[0;36m1[0m[0;34m,[0m [0mkeys[0m[0;34m=[0m[0;34m[[0m[0;34m'df1'[0m[0;34m,[0m [0;34m'df2'[0m[0;34m][0m[0;34m)[0m[0;34m.[0m[0mcorr[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mloc[0m[0;34m[[0m[0;34m'df2'[0m[0;34m,[0m [0;34m'df1'[0m[0;34m][0m[0;34m.[0m[0mT[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      6[0m [0;34m*[0m[0moutline[0m[0;34m,[0m [0m_[0m [0;34m=[0m [0mutil[0m[0;34m.[0m[0mget_outline[0m[0;34m([0m[0mcorr[0m[0;34m.[0m[0mvalues[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m [0max[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0;34m*[0m[0moutline[0m[0;34m,[0m [0mcolor[0m[0;34m=[0m[0;34m([0m[0;36m1[0m[0;34m,[0m[0;36m0[0m[0;34m,[0m[0;36m0[0m[0;34m,[0m[0;36m.5[0m[0;34m)[0m[0;34m,[0m [0mlinewidth[0m[0;34m=[0m[0;36m3[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/DevelopmentalRegulation/lib/python3.8/site-packages/pandas/core/indexing.py[0m in [0;36m__getitem__[0;34m(self, key)[0m
[1;32m    871[0m                     [0;31m# AttributeError for IntervalTree get_value[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m    872[0m                     [0;32mpass[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 873[0;31m             [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_getitem_tuple[0m[0;34m([0m[0mkey[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    874[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    875[0m             [0;31m# we by definition only have the 0th axis[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/DevelopmentalRegulation/lib/python3.8/site-packages/pandas/core/indexing.py[0m in [0;36m_getitem_tuple[0;34m(self, tup)[0m
[1;32m   1042[0m     [0;32mdef[0m [0m_getitem_tuple[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mtup[0m[0;34m:[0m [0mTuple[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1043[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1044[0;31m             [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_getitem_lowerdim[0m[0;34m([0m[0mtup[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1045[0m         [0;32mexcept[0m [0mIndexingError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1046[0m             [0;32mpass[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/DevelopmentalRegulation/lib/python3.8/site-packages/pandas/core/indexing.py[0m in [0;36m_getitem_lowerdim[0;34m(self, tup)[0m
[1;32m    784[0m                 [0;31m# We don't need to check for tuples here because those are[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m    785[0m                 [0;31m#  caught by the _is_nested_tuple_indexer check above.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 786[0;31m                 [0msection[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_getitem_axis[0m[0;34m([0m[0mkey[0m[0;34m,[0m [0maxis[0m[0;34m=[0m[0mi[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    787[0m [0;34m[0m[0m
[1;32m    788[0m                 [0;31m# We should never have a scalar section here, because[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/DevelopmentalRegulation/lib/python3.8/site-packages/pandas/core/indexing.py[0m in [0;36m_getitem_axis[0;34m(self, key, axis)[0m
[1;32m   1108[0m         [0;31m# fall thru to straight lookup[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1109[0m         [0mself[0m[0;34m.[0m[0m_validate_key[0m[0;34m([0m[0mkey[0m[0;34m,[0m [0maxis[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1110[0;31m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_get_label[0m[0;34m([0m[0mkey[0m[0;34m,[0m [0maxis[0m[0;34m=[0m[0maxis[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1111[0m [0;34m[0m[0m
[1;32m   1112[0m     [0;32mdef[0m [0m_get_slice_axis[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mslice_obj[0m[0;34m:[0m [0mslice[0m[0;34m,[0m [0maxis[0m[0;34m:[0m [0mint[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/DevelopmentalRegulation/lib/python3.8/site-packages/pandas/core/indexing.py[0m in [0;36m_get_label[0;34m(self, label, axis)[0m
[1;32m   1057[0m     [0;32mdef[0m [0m_get_label[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mlabel[0m[0;34m,[0m [0maxis[0m[0;34m:[0m [0mint[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1058[0m         [0;31m# GH#5667 this will fail if the label is not present in the axis.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1059[0;31m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0mobj[0m[0;34m.[0m[0mxs[0m[0;34m([0m[0mlabel[0m[0;34m,[0m [0maxis[0m[0;34m=[0m[0maxis[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1060[0m [0;34m[0m[0m
[1;32m   1061[0m     [0;32mdef[0m [0m_handle_lowerdim_multi_index_axis0[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mtup[0m[0;34m:[0m [0mTuple[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/DevelopmentalRegulation/lib/python3.8/site-packages/pandas/core/generic.py[0m in [0;36mxs[0;34m(self, key, axis, level, drop_level)[0m
[1;32m   3486[0m             [0mloc[0m[0;34m,[0m [0mnew_index[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mindex[0m[0;34m.[0m[0mget_loc_level[0m[0;34m([0m[0mkey[0m[0;34m,[0m [0mdrop_level[0m[0;34m=[0m[0mdrop_level[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   3487[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 3488[0;31m             [0mloc[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mindex[0m[0;34m.[0m[0mget_loc[0m[0;34m([0m[0mkey[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   3489[0m [0;34m[0m[0m
[1;32m   3490[0m             [0;32mif[0m [0misinstance[0m[0;34m([0m[0mloc[0m[0;34m,[0m [0mnp[0m[0;34m.[0m[0mndarray[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/DevelopmentalRegulation/lib/python3.8/site-packages/pandas/core/indexes/base.py[0m in [0;36mget_loc[0;34m(self, key, method, tolerance)[0m
[1;32m   2891[0m                 [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_engine[0m[0;34m.[0m[0mget_loc[0m[0;34m([0m[0mcasted_key[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2892[0m             [0;32mexcept[0m [0mKeyError[0m [0;32mas[0m [0merr[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 2893[0;31m                 [0;32mraise[0m [0mKeyError[0m[0;34m([0m[0mkey[0m[0;34m)[0m [0;32mfrom[0m [0merr[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   2894[0m [0;34m[0m[0m
[1;32m   2895[0m         [0;32mif[0m [0mtolerance[0m [0;32mis[0m [0;32mnot[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mKeyError[0m: 'df2'
KeyError: 'df2'

